Repository Davoleo/Metallurgy-4-Reforged, pull requests merged in 2018-11, with the labels that each got.

#18 Fixed exp bug, minor exp optimizations, machine slot refactoring
  src/main/java/it/hurts/metallurgy_5/container/ContainerAlloyer.java
  src/main/java/it/hurts/metallurgy_5/container/ContainerCrusher.java
  src/main/java/it/hurts/metallurgy_5/container/slot/SlotAlloyerOutput.java
  src/main/java/it/hurts/metallurgy_5/container/slot/SlotCrusherOutput.java
  src/main/java/it/hurts/metallurgy_5/util/Utils.java
  src/main/java/it/hurts/metallurgy_5/util/recipe/BlockAlloyerRecipes.java
  src/main/java/it/hurts/metallurgy_5/util/recipe/BlockCrusherRecipes.java
Labels: Needs Verification, Priority: Low, bug

#22 Alloyer GUI Fix and sulfur dust rework
  src/main/resources/assets/m5/textures/gui/alloyer.png
  src/main/resources/assets/m5/textures/items/dust_sulfur.png
Labels: Priority: High, enhancement, good first issue

#32 Fixed Machines Properties [Davoleo#25]
  src/main/java/it/hurts/metallurgy_5/block/BlockAlloyer.java
  src/main/java/it/hurts/metallurgy_5/block/BlockCrusher.java
Labels: Priority: Average, bug, good first issue

#37 #34 and alloyer recipe fix
  src/main/java/it/hurts/metallurgy_5/Metallurgy_5.java
  src/main/java/it/hurts/metallurgy_5/util/MetallurgyTabs.java
  src/main/java/it/hurts/metallurgy_5/util/handler/CommonTickHandler.java
  src/main/java/it/hurts/metallurgy_5/util/handler/EventHandler.java
  src/main/java/it/hurts/metallurgy_5/util/recipe/BlockAlloyerRecipes.java
Labels: Priority: Average, bug

#36 New Deep Iron Armor Effect and New Vampirism Effect for the Sanguinite Sword
  src/main/java/it/hurts/metallurgy_5/util/handler/EventHandler.java
Labels: Priority: High

#39 Fixed Server Crash Issues
  src/main/java/it/hurts/metallurgy_5/proxy/ClientProxy.java
  src/main/java/it/hurts/metallurgy_5/proxy/CommonProxy.java
  src/main/java/it/hurts/metallurgy_5/util/Tooltips.java
  src/main/java/it/hurts/metallurgy_5/util/handler/EventHandler.java
Labels: Priority: Average, bug

#40 Optimized Vulcanite Armor Effect
  src/main/java/it/hurts/metallurgy_5/util/handler/EventHandler.java
Labels: Priority: Average, bug, enhancement, good first issue

#48 Optimized Mithril Armor Effect and Deep Iron Armor
  src/main/java/it/hurts/metallurgy_reforged/util/handler/CustomSlot.java
  src/main/java/it/hurts/metallurgy_reforged/util/handler/EventHandler.java
Labels: Needs Verification, Priority: Average, enhancement
