Repository Davoleo/Metallurgy-4-Reforged, pull requests merged in 2018-12, with the labels that each got.

#64 Fixed Oureclase bug
  src/main/java/it/hurts/metallurgy_reforged/item/tool/ModTools.java
Labels: bug

#66 JEI Integration
  build.gradle
  src/main/java/it/hurts/metallurgy_reforged/gui/GuiAlloyer.java
  src/main/java/it/hurts/metallurgy_reforged/integration/IntegrationJEI.java
  src/main/java/it/hurts/metallurgy_reforged/integration/mods/jei/alloyer/AlloyerRecipeCategory.java
  src/main/java/it/hurts/metallurgy_reforged/integration/mods/jei/alloyer/AlloyerRecipeWrapper.java
  src/main/java/it/hurts/metallurgy_reforged/integration/mods/jei/crusher/CrusherRecipeCategory.java
  src/main/java/it/hurts/metallurgy_reforged/integration/mods/jei/crusher/CrusherRecipeWrapper.java
  src/main/java/it/hurts/metallurgy_reforged/util/recipe/BlockAlloyerRecipes.java
  src/main/java/it/hurts/metallurgy_reforged/util/recipe/BlockCrusherRecipes.java
  src/main/resources/assets/m5/lang/en_us.lang
Labels: Mod Integration, Priority: High, enhancement

#79 Inolashite Punch Armor Effect
  src/main/java/it/hurts/metallurgy_reforged/Metallurgy.java
  src/main/java/it/hurts/metallurgy_reforged/config/EffectsConfig.java
  src/main/java/it/hurts/metallurgy_reforged/util/capabilities/punch/IPunchEffect.java
  src/main/java/it/hurts/metallurgy_reforged/util/capabilities/punch/PunchEffect.java
  src/main/java/it/hurts/metallurgy_reforged/util/capabilities/punch/PunchEffectCallable.java
  src/main/java/it/hurts/metallurgy_reforged/util/capabilities/punch/PunchEffectProvider.java
  src/main/java/it/hurts/metallurgy_reforged/util/capabilities/punch/PunchEffectStorage.java
  src/main/java/it/hurts/metallurgy_reforged/util/handler/EventHandler.java
  src/main/java/it/hurts/metallurgy_reforged/util/handler/RegistrationHandler.java
  src/main/resources/assets/metallurgy/lang/en_us.lang
Labels: Priority: Average, enhancement
